In [26]:
import numpy as np

m=([[0, 1, 2],

   [3, 4, 5],

[6, 7, 8]])


In [27]:
m=[0, [1, 2]]
      


In [28]:
import pandas as pd



In [29]:
seri=pd.Series([22,32,45,67,21]) ## İNDİSLERİDE GÖSTERİYOR

In [30]:
type(seri)

pandas.core.series.Series

In [31]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [32]:
seri.dtype

dtype('int64')

In [33]:
seri.value_counts

<bound method IndexOpsMixin.value_counts of 0    22
1    32
2    45
3    67
4    21
dtype: int64>

In [34]:
seri.size

5

In [35]:
l=([12,34,54,123,])
pd.DataFrame(l,columns=["değişken ismi"])

değişken ismi
0             12
1             34
2             54
3            123

In [36]:
import numpy as np 
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
pd.DataFrame(m,columns=  ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [41]:
df=pd.DataFrame(m,columns=  ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [43]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [44]:
df.columns=["deg1","deg2","deg3"]

In [45]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [46]:
type(df)

pandas.core.frame.DataFrame

In [47]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [48]:
df.size

9

In [54]:
df.tail(3)


deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [59]:
import numpy as np 
m=np.arange(1,16).reshape((3,5))
m


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [69]:
df=pd.DataFrame(m,columns=  ["veri1","veri2","veri3","veri4","veri5"])

index=["a","b","c","d","e"]
df

veri1  veri2  veri3  veri4  veri5
0      1      2      3      4      5
1      6      7      8      9     10
2     11     12     13     14     15

In [76]:
df

veri1  veri2  veri3  veri4  veri5
0      1      2      3      4      5
1      6      7      8      9     10
2     11     12     13     14     15

In [85]:
df.drop([0], inplace=True)

In [87]:
df

veri1  veri2  veri3  veri4  veri5
1      6      7      8      9     10
2     11     12     13     14     15

In [98]:
a=np.arange(0,12).reshape((4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [101]:
df=pd.DataFrame(a, columns=["sütun1","sütun2","sütun3"])
df

sütun1  sütun2  sütun3
0       0       1       2
1       3       4       5
2       6       7       8
3       9      10      11

In [106]:
df.add([10,9,3]) ## toplaama


sütun1  sütun2  sütun3
0      10      10       5
1      13      13       8
2      16      16      11
3      19      19      14

In [107]:
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['sütun1', 'sütun2', 'sütun3'], dtype='object')]

In [108]:
df.info

<bound method DataFrame.info of    sütun1  sütun2  sütun3
0       0       1       2
1       3       4       5
2       6       7       8
3       9      10      11>

In [109]:
df.add

<bound method DataFrame.add of    sütun1  sütun2  sütun3
0       0       1       2
1       3       4       5
2       6       7       8
3       9      10      11>

In [110]:
df.plot

In [3]:
import numpy as np
import pandas as pd 
m=np.random.randint(1,30, size=(10,5))
df=pd.DataFrame(m, columns=["var1","var2","var3","var4","var5"])

In [4]:
df

var1  var2  var3  var4  var5
0    15     4     9    14     3
1    28     9    28    22    14
2    23    26     6    21     6
3     2    23     5    12    12
4    20    19     5    11     3
5     3     7    26     1     4
6    24    23     2     5    21
7     9     1    19    10    26
8    28    12    23    27     7
9     5    21    27    22     2

In [8]:
df2=df+99

In [9]:
df2

var1  var2  var3  var4  var5
0   114   103   108   113   102
1   127   108   127   121   113
2   122   125   105   120   105
3   101   122   104   111   111
4   119   118   104   110   102
5   102   106   125   100   103
6   123   122   101   104   120
7   108   100   118   109   125
8   127   111   122   126   106
9   104   120   126   121   101

In [13]:
pd.concat([df,df2],ignore_index=True) ##ignore index 0dan 19a kadar sıralı olmasını sağladı false olsa sıralı olmayacaktı 


var1  var2  var3  var4  var5
0     15     4     9    14     3
1     28     9    28    22    14
2     23    26     6    21     6
3      2    23     5    12    12
4     20    19     5    11     3
5      3     7    26     1     4
6     24    23     2     5    21
7      9     1    19    10    26
8     28    12    23    27     7
9      5    21    27    22     2
10   114   103   108   113   102
11   127   108   127   121   113
12   122   125   105   120   105
13   101   122   104   111   111
14   119   118   104   110   102
15   102   106   125   100   103
16   123   122   101   104   120
17   108   100   118   109   125
18   127   111   122   126   106
19   104   120   126   121   101

In [13]:
df=pd.DataFrame({
    'calisanlar':["Enes","Ahmet Yasin", "Ramazan"],  
    'grup':["Machine learning","IT","Data Science"]
})

In [14]:
df2=pd.DataFrame({
    'calisanlar':["Enes","Ahmet Yasin", "Ramazan"],  
    'ilk_giris':[2022,2020,2021]
})

In [15]:
df3=pd.merge(df,df2)
df3

calisanlar              grup  ilk_giris
0         Enes  Machine learning       2022
1  Ahmet Yasin                IT       2020
2      Ramazan      Data Science       2021

In [17]:
df4=pd.DataFrame({'grup':["Machine learning","IT","Data Science"],
       'müdür':["CANER","MUSTAFA","ALİ HAYDAR"]  
})
df4

grup       müdür
0  Machine learning       CANER
1                IT     MUSTAFA
2      Data Science  ALİ HAYDAR

In [19]:
df5=pd.merge(df3,df4)

In [20]:
df5

calisanlar              grup  ilk_giris       müdür
0         Enes  Machine learning       2022       CANER
1  Ahmet Yasin                IT       2020     MUSTAFA
2      Ramazan      Data Science       2021  ALİ HAYDAR

In [21]:
#AGGREGITAION AND GROUPING 
import seaborn as sns
?sns.load_dataset

    

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [22]:
df=sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [23]:
df.shape

(1035, 6)

In [24]:
df["mass"].mean()

2.6381605847953216

In [25]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [26]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [27]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [28]:
?groupby

Object `groupby` not found.


In [29]:
import numpy as np
import pandas as pd 
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [6]:
import numpy as np
import pandas as pd 

In [58]:
import pandas as pd 
df=pd.DataFrame({
    'Gruplar':["A","B","C","D"],
    'Kişiler':["Enes","Ahmet","Ramazan","Deniz"],
    'Maaş': ["5000USD","5000USD","5000USD","5000USD"]},
     columns = ['Gruplar','Kişiler','Maaş']
)    


In [61]:
df

Gruplar  Kişiler     Maaş
0       A     Enes  5000USD
1       B    Ahmet  5000USD
2       C  Ramazan  5000USD
3       D    Deniz  5000USD

In [60]:
df.describe

<bound method NDFrame.describe of   Gruplar  Kişiler     Maaş
0       A     Enes  5000USD
1       B    Ahmet  5000USD
2       C  Ramazan  5000USD
3       D    Deniz  5000USD>

In [69]:
data=pd.read_csv("reading_data/ornekcsv.csv",sep=";")    

In [70]:
data

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [71]:
type(data)

pandas.core.frame.DataFrame

In [72]:
data.columns

Index(['a', 'b', 'c'], dtype='object')